name: Deploy Secrets

on: push

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Create secret file
      run: echo "{\"secret\":\"${{ secrets.MY_SECRET }}\"}" > secret.json

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        folder: .